name: aitrip
description: あいトリップ
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  firebase_auth: ^5.1.2
  firebase_ui_auth: ^1.9.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  font_awesome_flutter: ^10.7.0
  webview_flutter: ^4.7.0
  google_fonts: ^6.2.1
  flutter_chat_bubble: ^2.0.2
  speech_to_text: ^6.6.0
  settings_ui: ^2.0.2
  flutter_tts: ^4.0.2
  freezed_annotation: ^2.4.1
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/.env
